# Generated by Django 5.0.14 on 2026-07-01 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='evidences/')),
                ('file_hash', models.CharField(blank=True, max_length=64, verbose_name='Hash SHA-256')),
                ('file_size', models.IntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('content_type', models.CharField(blank=True, max_length=150, verbose_name='Tipo MIME')),
                ('encrypted_notes', models.TextField(blank=True, verbose_name='Notas encriptadas en reposo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
