# Generated by Django 5.0.14 on 2026-07-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signature_image',
            field=models.FileField(blank=True, null=True, upload_to='signatures/', verbose_name='Firma Manuscrita'),
        ),
    ]
